### ISSUE TITLE
can someone help me when i configure libirecovery i get this error

### ISSUE THREAD

**Issue by shawn7226791** [nfc-tools/libnfc#571] opened 2019-10-29 16:17 UTC
./configure: line 6664: syntax error near unexpected token `libusb,'
./configure: line 6664: `			PKG_CHECK_MODULES(libusb, libusb-1.0 >= $LIBUSB_VERSION)'

**Comment by mkapln2** [comment] 2020-03-02 13:22
same

**Comment by thekix** [comment] 2020-03-02 13:55
Hi,

nfc-tools uses libusb to connect with the devices. You need include libusb (devel files) in your system to compile nfc-tools.

For example, in debian/ubuntu you can do it using:

apt-get install libusb-dev

Regards,
kix

**Comment by thekix** [comment] 2020-03-03 08:10
@mkapln2 @shawn7226791 if the problem is solved, please, close the bug.

Regards,
kix

**Comment by neomilium** [comment] 2021-01-04 20:43
@thekix Thanks for your help.
No reply from author, closing issue.

**Closed by neomilium** 2021-01-04 20:43 UTC
